Refactor/sign up #141
telling-me/tellingme-iOS pull request #144
Opened 2023-10-04 03:14 UTC by akrudal

### 📃 전달 사항
- 컨벤션 적용 후에 작성하도록 하겠습니다!
어떤 버그나 오류가 발생했는지, 무슨 이유로 코드를 생성하거나 변경했는지, 어떤 부분을 집중적으로 봐줘야하는지 등
상세 내용을 적어주세요.

### 📸 스크린샷

### ✔ 진행사항
- [ ] done1
- [ ] done1

### 🔴 ETC
기타 사항을 적어주세요.
실제 개발 기간 : 

### 💻 개발환경
macOS: Monterey 12.0.1
iOS: iphone 11 pro simulator

<hr>

closes: #

2023-10-04 17:24 UTC, PecanPiePOS requested changes
추석까지 껴서 고생 많으셨습니다!
p1 부분이 2개나 있어서 Approve 를 할 수는 없어서 Request Changes 로 코드 리뷰 마치겠습니다!
다시 한번 리펙터링 힘드셨을텐데 고생하셨습니다.

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/Assets.xcassets/svg/button/etc/Checkbox.imageset/Contents.json
> +}
p3
여기에 표시가 안되어 있는데, 혹시 제가 드린 탭 icon 이 안들어가 있나요?? ㅠㅜ 
제가 손수 수정한... 에셋들... 후....

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/base/BaseViewController.swift
>  }
p4
기존에 있는 UIViewController 메서드 중에서 TouchesEnded 를 활용한 키보드 내리는 것과 추가해주신 메서드와는 어떤 차이가 있을까용??

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/common/component/BoxCheckboxView.swift
> +    }
p2
UIView 에서는 특별한 이유가 없이는 deinit 이 필요하지 않습니다! 지워주세용!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/common/component/BoxCheckboxView.swift
> +    }
p3
쓰이지 않는 함수니깐 지워주셔도 될 것 같습니다~!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/common/component/BoxCheckboxView.swift
> +import RxSwift
p3
Rx가 사용되지 않아 필요 없을 것 같습니다!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/common/header/LogoHeaderView.swift
> +class LogoHeaderView: UIView {
p2
혹시 LogoHeaderView 가 상속을 하나요??

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/common/nicknameInput/NickNameInputViewController.swift
>      }
p2
혹시 제가 지금 이 pr 에서는 찾을 수 없는 것 같은데 `NickNameInputViewController` 가 다른 class 에 상속하나요??
그게 아니라 final 이 들어가는 것이 적합해보입니다!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/AgreementBottomSheetViewController.swift
> +    }
p5
😃👍🏻

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpBaseViewController.swift
> +    }
p3
이건 어디서 필요한걸까용??

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +    private let disposeBag = DisposeBag()
p4
윗줄 붙이셔도 될 것 같습니다~!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +            .throttle(.milliseconds(1000), scheduler: MainScheduler.instance)
p1
`throttle()` 에 parameter 중에서, latest 라는 parameter 가 있습니다.
`.throttle(.seconds(3), latest: false)` 이런 형식인데요.
`latest` 의 default 값은 `true` 입니다. 즉, 1000밀리초(1초) 내로 두 번을 누르게 되면 latest tap 값이 한번 더 들어가서 총 2번이 찍히게 됩니다. 1초 내로 3번을 눌러도 2번이 들어갑니다. 하지만, 저희는 중복 값을 막는것이 목적이므로 아마 빠르게 두번 누르시면 페이지 이동이 한번 더 되는걸 볼 수 있으실겁니다! 설령 그렇지 않더라도 ux 상의 버그가 언제든 생길 수 있는 컴포넌트이기 때문에 false 로 바꾸는걸 추천 드립니다!
```suggestion
            .throttle(.milliseconds(1000), latest: false, scheduler: MainScheduler.instance)
```

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +            .throttle(.milliseconds(1000), scheduler: MainScheduler.instance)
p1
throttle 이 사용된 곳에서는 위에서 언급된 것과 같이 모두 바꿔주시기 바랍니다!
아래에도 다 바꿔주시면 될 것 같습니다!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +                         leftButton, rightButton, infoview)
p5
LGTM

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/pages/AgreementViewController.swift
> +    }
p4
이것도 그 컨벤션에 적었어야 했던것 같은데 죄송합니다 ㅠㅜ
required init 은 맨 아래로 내려주시면 감사하겠습니다! deinit 아래이든 위이든요!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/pages/AgreementViewController.swift
> +            guard let checkboxView = checkboxView as? CheckboxView else {
p4
BoxCheckBoxView 를 굳이이 CheckboxView 로 타입캐스팅을 하신 이유가 어떤걸까용???

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +extension SignUpViewController: UIPageViewControllerDelegate, UIPageViewControllerDataSource {
p3
UIPageViewControllerDataSource 를 채택하게 되면, 손으로 스와이프가 가능하다고 알고 있는데 혹시 손으로 스와이프가 막혀있나요?!?!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +                    viewModel.inputs.checkNickname()
p4
그러면 아이디 체크는 적은 후에 저절로 되는게 아니라
다음 버튼을 눌러야 되는거군요?!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/presentation/signUp/views/BottomInfoView.swift
> +import SnapKit
p5
마찬가지로 안쓰는 메서드와 함께 지워주시면 감사하겠습니다!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/util/custom/style/Input.swift
>  class Input: UIView {
p1
final 을 붙이셔도 될 것 같구요
class 의 이름이 너무 모호한 것 같습니다.. ㅠ 처음에 `NickNameInputViewController` 에서 **`Input()`** 이라는 객체를 보고 이게 어떤 건지 감이 전혀 잡히지 않았습니다. 특히, 시스템이나 VM 에서 쓰이는 용어와 너무 비슷하기 때문에 이건 꼭 다른 class 명으로 바꿔주시는게 좋다고 생각합니다!!

2023-10-04 17:24 UTC, PecanPiePOS commented on TellingMe/tellingMe/util/nameSpace/StringLiteral.swift
> +}
p3
아 ㅎ 제가 또 수정한 파일이 있어서, 그것도 함께 수정해주시면 감사하겠습니다 ㅎㅎ
지금 이게 확인하는 마지막 파일인데 이거 적고 review 작성하고 슬랙으로 바로 드리겠습니다~!

2023-10-04 17:46 UTC, akrudal commented on TellingMe/tellingMe/presentation/base/BaseViewController.swift
>  }
기존 메서드는 touchesEnded로 터치영역에 관한 것이었고 이번에 추가한건 uitapgesturerecognizer입니다!
이렇게 하게되면, 키보드가 필요한 뷰컨트롤러에서 hideKeyboardWhenTappedAround()를 불러주기만 하면 추가가 됩니다.

베이스뷰컨트롤러도 만들었으니 재사용되면 더욱 편할 것 같아서 조금 더 간편한 방법 찾아왔습니다.

2023-10-04 17:46 UTC, akrudal commented on TellingMe/tellingMe/util/custom/style/Input.swift
>  class Input: UIView {
기존에 만들어두었던 것이라서 리팩토링과정에서 시간이 없어서 그냥 넘겼습니다!
수정하도록 하겠습니다~

2023-10-04 17:48 UTC, akrudal commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpBaseViewController.swift
> +    }
이건 필요한 초기화함수입니다!
signupbaseviewcontroller를 상속받는 함수들이 viewModel 의존성을 추가해야되면서 init 메서드가 필요하게 되고 그러면 override init()이 필요하게 됩니다

2023-10-04 17:50 UTC, akrudal commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +extension SignUpViewController: UIPageViewControllerDelegate, UIPageViewControllerDataSource {
넵 막혀있습니당~

2023-10-04 17:50 UTC, akrudal commented on TellingMe/tellingMe/presentation/signUp/viewControllers/SignUpViewController.swift
> +                    viewModel.inputs.checkNickname()
넵 기존에 그렇게 상의되어있었습니다!

2023-10-05 05:05 UTC, akrudal commented on TellingMe/tellingMe/presentation/common/header/LogoHeaderView.swift
> +class LogoHeaderView: UIView {
넵! 리팩토링 기간이라 헤더까지 신경쓰진 않았지만 현재 홈화면 스토리보드에 연결되어있는 MainHeaderSettingView가 있습니다! 
홈 화면 리팩토링 머지 후에 setttingHeaderView 제거하고 LogoHeaderView에 final 붙이도록 하겠습니다.!

2023-10-05 05:07 UTC, akrudal commented on TellingMe/tellingMe/presentation/common/nicknameInput/NickNameInputViewController.swift
>      }
현재 리팩토링에 포함되지 않는 뷰컨트롤러입니다! 아마 내 정보수정하기에서 사용되는 뷰컨트롤러인 것 같습니다.
final은 붙여뒀으나 inputBox가 이름이 변경되면서 변경내용에 포함된 것이니 이번 리팩토링과 관련 없이 추후 리팩토링에 신경써야될 부분 같습니다~! :)

2023-10-05 05:10 UTC, akrudal commented on TellingMe/tellingMe/presentation/signUp/viewControllers/pages/AgreementViewController.swift
> +            guard let checkboxView = checkboxView as? CheckboxView else {
stackview에서 arrangedSubviews를 사용하면 그냥 UIView 배열을 return 합니다!
따라서 checkboxview안에 있는 checkButton에 접근하기 위해서 타입캐스팅을 하였습니다

2023-10-05 05:29 UTC, akrudal commented on TellingMe/tellingMe/Assets.xcassets/svg/button/etc/Checkbox.imageset/Contents.json
> +}
에셋 지금은 넣었습니다...죄송합니다 ㅎㅎ

2023-10-05 06:45 UTC, PecanPiePOS approved these changes
고생하셨습니다!

2023-10-05 06:46 UTC, merged